### ISSUE TITLE
[klitmus] Linux v5.17 stopped exporting do_exit()

### ISSUE THREAD

**Issue by akiyks** [herd/herdtools7#372]
Hi,

I could have reported this issue earlier, but noticed it after updating the distro kernel packages
on a Fedora 35 machine.

Now, building kernel modules generated by klitmus7 ends up in errors from modpost:

```
[...]
ERROR: modpost: "do_exit" [/<path to klitmus7 output>/litmus002.ko] undefined!
ERROR: modpost: "do_exit" [/<path to klitmus7 output>/litmus001.ko] undefined!
ERROR: modpost: "do_exit" [/<path to klitmus7 output>/litmus000.ko] undefined!
```
This is because Linux kernel no longer exports do_exit().  The change were done by
one of the changes pulled into mainline by merge commit 35ce8ae9ae2
("Merge branch 'signal-for-v5.17' of git://git.kernel.org/pub/scm/linux/kernel/git/ebiederm/user-namespace")

I've not figured out which exported API to use instead, though.

All I can do for now is to report the issue.

**Comment by akiyks** [comment]
It looks like you don't need do_exit(0) at the end of a kthread function.
Simple "return 0;" should suffice.

So, I tested the change below:

```
diff --git a/litmus/KSkel.ml b/litmus/KSkel.ml
index d425164ceb8e..24bde3ca4345 100644
--- a/litmus/KSkel.ml
+++ b/litmus/KSkel.ml
@@ -674,7 +674,7 @@ let dump_threads _tname env test =
       O.oi "smp_mb();" ;
       O.oi "wake_up(wq);" ;
       O.oi "smp_mb();" ;
-      O.oi "do_exit(0);" ;
+      O.oi "return 0;" ;
       O.o "}" ;
       O.o "" ;
       ())
```
It works with Linux v5.17 as well as older releases of Linux kernels.

Can you do a point release with this fix applied to 7.56?
It looks to me like 7.57 is still in its stabilization phase, so.

**Comment by maranget** [comment]
Hi @akiyks. Thanks for the report and patch. Integrated by PR #374.

**Comment by akiyks** [comment]
Thanks!

So, when can I expect a release with this fix?
I need to send a patch for updating compat table in LKMM's README.

**Comment by maranget** [comment]
Here is the [release](https://github.com/herd/herdtools7/releases/tag/7.56.1).
This is 7.56 with your fix applied.

**Comment by akiyks** [comment]
Nice!
Thank you for the quick release.
Closing this issue now.

**Comment by akiyks** [comment]
Hi @maranget.

I'm wondering why `opam update` don't see 7.56.1 yet.
I also tried clean install of herdtools7 by `opam install` from scratch, and 7.56 is the version installed.
What am I missing?

**Comment by maranget** [comment]
Hi Akira, 

Submission to opam is on its war, I simply forgot to submit, sorry for that and thanks for the reminder. 

--Luc

**Comment by akiyks** [comment]
Ah, that explains.

Now I see there are several CI test failures at opam-repository.
I did see similar warnings in building 7.56.1.

```
$ make all
sh ./dune-build.sh $HOME
File "lib/check402.ml", line 1:          
Warning 70 [missing-mli]: Cannot find interface file.
File "lib/echo.ml", line 1:             
Warning 70 [missing-mli]: Cannot find interface file.
File "lib/myMap.ml", line 1:             
Warning 70 [missing-mli]: Cannot find interface file.
File "lib/location.ml", line 1:          
Warning 70 [missing-mli]: Cannot find interface file.
[...]
``` 
Building current master doesn't emit such warnings.
You might need to backport (a) fix.

**Comment by maranget** [comment]
Thanks, @akiyks going back in time was not that easy...

**Comment by akiyks** [comment]
git bisect points to commit a2725b77081a which silences these warnings.
I think this one is not hard to backport, but cherry-picking only this one ended up in:
```
$ make all
sh ./dune-build.sh $HOME
File "lib/testHash.ml", line 189, characters 46-59:
189 |         let pp = String.concat "; " (List.map dump_location locs) in
                                                    ^^^^^^^^^^^^^
Error: Unbound value dump_location
File "tools/dumperMiscParser.ml", line 43, characters 25-32:
43 |                (fun a -> sprintf "%s;" (dump_state_atom a))
                              ^^^^^^^
Error: Unbound value sprintf
File "tools/dumper.ml", line 33, characters 25-32:
33 |                (fun a -> sprintf "%s;" (dump_atom_state a))
                              ^^^^^^^
Error: Unbound value sprintf
```
I think this is all I can do as I'm not an ocaml programmer.

**Comment by maranget** [comment]
Patching the dune file was enough (top of [commit](https://github.com/herd/herdtools7/commit/a2725b77081a85fb259280deeb29a7ed39519989).

Version 7.56.1 has been accepted on opam and should be  available soon.

Thanks again

**Comment by akiyks** [comment]
Now I've got 7.56.1 through `opam update; opam upgrade`.
Closing again.
Thanks!

**Comment by akiyks** [comment]
One more comment.

It would be better to move (`push -f`) the tag `7.56.1` to the branch's HEAD.

**Comment by maranget** [comment]
Hi, 

Sorry for any inconvenience but I do not understand. 

There are both a branch (7.56.1-release) and a tag (7.56.1) and they look synchronised in the github deposit --- I mean they point to the same commit ---, although the ordering of the commits themselves may lack of clarity. 

I any case I am willing to follow good practice, but I lack the knowledge and easy access to knowledgeable people. 

Best, 

--Luc

**Comment by akiyks** [comment]
Apologies...

It turns out that I need to use `git fetch -P` so that local tag of the same name is
pruned before fetching the tag you have updated.

Sorry for the noise.
